### ISSUE TITLE
Multiple git projects

### ISSUE THREAD

**Issue by karelb** [olmokramer/atom-tree-view-git-branch#7]
If you have multiple git  projects in your treeview it opens a "local branches" fore each of them. Adding or removing a project will sort the treeview and all "local branches" are grouped.

An indication of the project where it belongs too might be useful. eg.
- ProjectA branches or
- local branches (ProjectA)

Or even better ( no clue if this is possible) as first item inside the project view:
ProjectA
- local branches
- project dirs + files

Regards

Karel

**Comment by olmokramer** [comment]
Hi Karel,

Thanks for your report. I don't use the multiple projects feature very often, so I hadn't noticed this before.

This is definitely not intended behavior. Each `local branches` should be right before the corresponding project directory. I tried adding them as the first item in the directory, but that is quite tricky, because when you collapse the directory, the `tree-view` package actually removes the element from the DOM. I can probably detect when a directory is collapsed/expanded, but then I would very much rely on the internals of `tree-view` which is something I'd rather avoid.

If that is possible I'll go with it, but I like the indication of which project the branches belong to as well. I'll probably go with `local branches (projectA)` because I intend to support `remote branches` and `tags` as well in the future. Maybe I'll drop the `branches` part, as the icon makes it quite obvious.

I'll try to look into this next weekend.

**Comment by karelb** [comment]
Hi Olmo,

I agree that inside the directory tree would be a very nice feature. 
But the alternative is fine with me as well. 

And actually it would not even be a bad feature if all local (Project) and remote (Project)  trees are grouped together on top, before all projects trees. This will leave the same functionality nicely grouped together.

Anyway, I am looking forward to see your new layout, whatever you decide it will be.

Groet
Karel

**Comment by laughedelic** [comment]
Any updates here?

**Comment by pdxwolfy** [comment]
I was about to mention my own concerns about the way multiple projects are handled visually, but after reading the above, I got the idea to tweak the styling. I added the following:

```
.tree-view .icon-git-branch {
    padding-top: 1em;
    margin: 1em auto 0.5em auto;
    border-top: 1px solid white;
    width: 100%;
}
```

to my styles.less file. It gives a nice visual way to distinguish which "local branches" belongs where. Feel free to steal and use for whatever purpose.  (I'm not entirely sure whether the "width: 100%" will break anything - if it does, just remove it.)  (I would like to find a way to remove the divider line at the very top of the tree, but...)

![screen shot 2015-12-20 at 10 36 41](https://cloud.githubusercontent.com/assets/16280491/11919368/b345942a-a705-11e5-81bb-6f4273b3460d.jpg)

**Comment by bean5** [comment]
My "local branches" end up all bunched together. I'm guessing it is because I am using https://atom.io/packages/project-manager

![image](https://cloud.githubusercontent.com/assets/2052646/13233778/a0aeef42-d972-11e5-9bf4-96c2fa5d3768.png)

**Comment by olmokramer** [comment]
I've just published a new version that adresses this issue. It also introduces a new `location` setting that controls the location of the branches in the tree view. You can choose between `top` and `before-project`. The former places all branches at the top of the tree view, the latter places them before their corresponding project.

@pdxwolfy That's looks really helpful, so I've also added a setting `separator` that does the same thing. There's some styling already, but I also add a `.separator` class to the items in the tree view. You can customize it with:

``` less
.tree-view [is="tree-view-git-branch-list"].separator {
  border-top: 1px solid white;
}
```
