### ISSUE TITLE
Recent updates not working.

### ISSUE THREAD

**Issue by pdxwolfy** [olmokramer/atom-tree-view-git-branch#9]
In 0.1.0, the location option was added with before-project and top as options. Both options worked.  In 0.1.1, only top seems to work. With before-project and inside, the branches go away.

0.1.1 introduced the separator option. This option doesn't seem to work for me using 

```
   separator: true
```

I have also tried:

```
separator: {}
```

Also, for reasons as yet undetermined, the location option keeps disappearing from my settings - I've now had it cleared out 4 times.

**Comment by olmokramer** [comment]
Thanks for the report. Even though it worked fine for me, I did notice some errors in the code dealing with the placement. I've just published a new version, 0.1.2, that addresses those issues, so please let me know if it works for you.

The `separator` setting does nothing when the `location` setting is `top` (as it says now in the description), so if `before` or `inside` were hiding the branches for you I think that's why `separator` didn't seem to work either. If the `separator` setting still isn't working, could you try adding the following snippet to your `styles.less` and select either `before` or `inside` for the `location`.

``` less
.tree-view > li.separator {
  background-color: #f0f !important;
}
```

Regarding the option disappearing: I've renamed `before-project` to just `before`. So `before-project` is now an invalid value, in which case atom reverts to the default value for the option.

**Comment by pdxwolfy** [comment]
Thanks, Olmo. That seems to have done the trick.

**Comment by olmokramer** [comment]
Great! Thanks for letting me know

**Comment by pdxwolfy** [comment]
This can be closed, I think. (Not sure of the etiquette.)
